import "../../public/styles/globals.scss"
import {Manrope} from "next/font/google"
import {Provider} from "react-redux";
import {store} from "next/dist/build/output/store";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const manrope = Manrope({
  weight: ["500", "700"],
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
      <Provider store={store}>
        {children}
      </Provider>
      </body>
    </html>
  )
}
